name: Run unit tests
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run cmake
        run: cmake -B build/
      - name: Build code
        run: cmake --build build/
      - name: Run unit tests
        run: cmake --test-dir build/
        
