name: Run unit tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run cmake
        run: cmake -B build/
      - name: Build code
        run: cmake --build build/
      - name: Run unit tests
        run: ctest --test-dir build/ -V
